package_rename_config:
  android:
    app_name: DAU Footy Tipping
    package_name: coach.interview.daufootytipping
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: DAU Footy Tipping
    bundle_name: daufootytipping
    package_name: coach.interview.daufootytipping

  macos:
    app_name: DAU Footy Tipping
    package_name: coach.interview.daufootytipping
    copyright_notice: (c)2024 DAU Footy Tipping
